name: portfolio
description: My professional website and software portfolio
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  layout: 1.0.3
  google_fonts: 5.1.0 
  responsive_builder: 0.7.0
  visibility_detector: ^0.4.0
  url_launcher: 6.1.12
  flutter_feather_icons: 2.0.0+1
  font_awesome_flutter: 10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


